server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Permitir subida de archivos hasta 10MB
    client_max_body_size 10M;

    # Para React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia las APIs del backend (red interna AWS)
    location /api/productos/ {
        proxy_pass http://10.0.139.35:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/usuarios/ {
        proxy_pass http://10.0.139.35:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/pedidos/ {
        proxy_pass http://10.0.139.35:8083/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/carritos/ {
        proxy_pass http://10.0.139.35:8084/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    gzip on;
    gzip_types text/plain application/json application/javascript text/css;
}
